version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=scheduler_production
  web:
    image: fuxin/scheduler-service
    command: bash -c "python manage.py db upgrade && gunicorn manage:app --bind 0.0.0.0:8000"
    environment:
      - FLASK_ENV=production
    depends_on:
      - db
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
